---
title: 获取异步请求的返回值处理后的值
date: 2016-11-6 20:20:22
excerpt: 这是业务场景中经常遇到的一个问题，项目中，我们的异步请求(ajax, fetch...)往往会根据需要进行更深一层的封装，有时我们会想在调用请求时拿到异步返回的值，你可能会在项目中看到下面的代码，有时候他们甚至是可以正常运行的(将ajax设置成同步请求)。
---

这是业务场景中经常遇到的一个问题，项目中，我们的异步请求(ajax, fetch...)往往会根据需要进行更深一层的封装，有时我们会想在调用请求时拿到异步返回的值，你可能会在项目中看到下面的代码，有时候他们甚至是可以正常运行的(将ajax设置成同步请求)。

```js
// myAjax
function myAjax() {
  var data = [];
  $.ajax({
    url: '',
    type: 'post',
    data: '',
    success: function(res) {
      data = res.data;

      //want to
      return data; //this will fail
    }
  });

  return data;
}

// other place
...
var data = myAjax(); //of course get undefined
...
```

这其实是我们在项目中最常见的一个异步场景，在Promise出现之前，异步编程我们通过回调函数来完成。

## 利用回调函数(callback)实现

```js
// myAjax
function myAjax(data, successCbk, failCbk) {
  $.ajax({
    url: '',
    type: 'post',
    data: '',
    success: function(res) {
      var data = res.data;
      successCbk && successCbk(data);
    },
    fail: function(err) {
      failCbk && failCbk(err)
    }
  });

  return data;
}

// other place
...
myAjax({}, function(data){
  var resData = data;
  console.log(resData)
}, function(err){
  console.log(err)
}); 
...
```

看起来问题似乎解决了，但是后续依然可能面临其他问题。比如多个异步请求的顺序问题，callback 中依然包含异步过程的问题……这将把我们一步步带到回调地狱，你只能通过回调套回调来处理这些问题(或者去优化你的业务逻辑)。而我们的代码也会变得越来越难以理解和维护。而终于，我们有了 promise 来处理异步流程，甚至 jquery 的 ajax 也是支持的。

## 利用 promise 来处理

```js
// myAjax
function myAjax(data, successCbk, failCbk) {
  return $.ajax({
    url: '',
    type: 'post',
    data: ''
  }).then(
    function success(res) {
      return res.data;
    },
    function fail(err) {
      return err;
    }
  );
}

// other place
...
myAjax().then(
  (data) => {
    var newDef = $.Deferred();

    var resData = data;
    console.log(resData);

    return newDef.resolve(resData);
  },
  (err) => console.log(err)
).then(res => console.log(res)); 
...
```

> Promise 本质上是一个绑定了回调的对象，而不是将回调传进函数内部。

## 利用 async/await 语法糖

尽管 Promise 解决了我们回调地狱的问题，但是我们还是要在 `.then` 方法的函数内部去进行赋值操作，理想的异步操作的同步写法或许是这样的：

```js
var a = asyncGet(data); 
var b = asyncGet(a);
```

没错，就像一般的方法一样，风格统一。利用 `async/await` 就基本能实现这一功能，异常的捕捉都会变得非常简单。

```js
async function foo() {
  try {
    let result = await doSomething();
    let newResult = await doSomethingElse(result);
    let finalResult = await doThirdThing(newResult);
    console.log(`Got the final result: ${finalResult}`);
  } catch(error) {
    failureCallback(error);
  }
}

// 更简单的时序组合
for (let f of [func1, func2]) {
  await f();
}
```


